/**
 * `dsh service` (fork): unit rendering invariants, state derivation,
 * overwrite protection, and the per-platform command mapping against an
 * injected runner.
 */

import { chmodSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'
import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import { probeManagedService, readInstallState, renderLaunchdPlist, renderSystemdUnit, resolveUnit, runService, type InstallState, type UnitSpec } from '../src/service.ts'

const dirs: string[] = []

beforeEach(() => {
  delete process.env.DSH_SERVICE_UNIT
  delete process.env.DSH_INSTALL_STATE
})

afterEach(() => {
  for (const dir of dirs.splice(0)) rmSync(dir, { recursive: true, force: true })
  delete process.env.DSH_HOME
  delete process.env.DSH_SERVICE_UNIT
})

/** A temp dir for one test. */
function tempDir(): string {
  const dir = mkdtempSync(join(tmpdir(), 'dsh-service-'))
  dirs.push(dir)
  return dir
}

/** A sink captured as text. */
function sink(): { write: (chunk: string) => boolean; text: () => string } {
  let text = ''
  return { write: (chunk: string) => { text += chunk; return true }, text: () => text }
}

/** A recorded-runner pair. */
interface Calls {
  calls: Array<{ command: string; args: readonly string[] }>
  run: (command: string, args: readonly string[]) => number
}

/** Build a runner that records calls and answers per a matcher. */
function recorder(answer: (command: string, args: readonly string[]) => number = () => 0): Calls {
  const calls: Calls['calls'] = []
  return {
    calls,
    run: (command, args) => {
      calls.push({ command, args })
      return answer(command, args)
    },
  }
}

const spec: UnitSpec = {
  prefix: '/tmp/prefix',
  node: '/tmp/prefix/runtime/node/current/bin/node',
  bin: '/tmp/prefix/harness/current/apps/cli/lib/bin.js',
  dshHome: '/tmp/dshhome',
  port: 3080,
  binDir: '/tmp/prefix/bin',
}

describe('unit rendering', () => {
  it('renders a marker-guarded systemd unit that always serves in the foreground', () => {
    const text = renderSystemdUnit(spec)
    expect(text.startsWith('# Generated by dsh service install')).toBe(true)
    expect(text).toContain('ExecStart=/tmp/prefix/runtime/node/current/bin/node /tmp/prefix/harness/current/apps/cli/lib/bin.js web --foreground --host 127.0.0.1 --port 3080 --no-open')
    expect(text).toContain('Restart=on-failure')
    expect(text).toContain('Environment=DSH_HOME=/tmp/dshhome')
    expect(text).toContain('WantedBy=default.target')
  })

  it('renders a launchd plist with conditional keepalive and an explicit PATH', () => {
    const text = renderLaunchdPlist({ ...spec, label: 'com.enpoi.dsh-web', logPath: '/tmp/dshhome/logs/web.log' })
    expect(text).toContain('<!-- Generated by dsh service install -->')
    expect(text).toContain('<key>Label</key><string>com.enpoi.dsh-web</string>')
    expect(text).toContain('<string>--foreground</string>')
    expect(text).toContain('<key>RunAtLoad</key><true/>')
    expect(text).toContain('<key>SuccessfulExit</key><false/>')
    expect(text).toContain('<key>Crashed</key><true/>')
    expect(text).toContain('<key>PATH</key><string>/tmp/prefix/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>')
    expect(text).toContain('<key>DSH_HOME</key><string>/tmp/dshhome</string>')
    expect(text).toContain('<key>StandardOutPath</key><string>/tmp/dshhome/logs/web.log</string>')
  })
})

describe('state and unit resolution', () => {
  it('reads the installer state file', () => {
    const path = join(tempDir(), 'install-state.json')
    writeFileSync(path, JSON.stringify({ prefix: '/p', node: '/n', serviceUnit: 'u' }))
    expect(readInstallState(path)).toEqual({ prefix: '/p', node: '/n', serviceUnit: 'u' })
    expect(readInstallState(join(tempDir(), 'absent.json'))).toBeUndefined()
  })

  it('derives stable paths from the recorded prefix and home', () => {
    const home = tempDir()
    const state: InstallState = { prefix: '/tmp/prefix', node: '/usr/bin/node', binDir: '/tmp/prefix/bin', dshHome: '/tmp/dshhome' }
    const linux = resolveUnit(state, { platform: 'linux', home })
    expect(linux.unit).toBe('dsh-web.service')
    expect(linux.path).toBe(join(home, '.config', 'systemd', 'user', 'dsh-web.service'))
    expect(linux.spec.bin).toBe('/tmp/prefix/harness/current/apps/cli/lib/bin.js')
    const darwin = resolveUnit({ ...state, serviceUnit: 'com.example.dsh' }, { platform: 'darwin', home })
    expect(darwin.unit).toBe('com.example.dsh')
    expect(darwin.path).toBe(join(home, 'Library', 'LaunchAgents', 'com.example.dsh.plist'))
  })

  it('re-resolves a recorded node at generation time instead of templating a dead path', () => {
    const home = tempDir()
    const deadNode = join(tempDir(), 'removed-node-version', 'bin', 'node')
    const linux = resolveUnit({ prefix: '/tmp/prefix', node: deadNode, dshHome: '/tmp/dshhome' }, { platform: 'linux', home })
    // The recorded path no longer executes: the running binary is the durable
    // fallback, so a Node bump cannot orphan the generated unit.
    expect(linux.spec.node).toBe(process.execPath)
    expect(linux.content).not.toContain(deadNode)
  })

  it('treats a recorded node path that is a directory as unusable', () => {
    const home = tempDir()
    const asDirectory = tempDir()
    const linux = resolveUnit({ prefix: '/tmp/prefix', node: asDirectory, dshHome: '/tmp/dshhome' }, { platform: 'linux', home })
    // An executable directory bit must never be templated as a Node binary.
    expect(linux.spec.node).toBe(process.execPath)
  })

  it('prefers the runtime link, then an executable recorded node, over the running binary', () => {
    const home = tempDir()
    const prefix = tempDir()
    const recorded = join(tempDir(), 'node')
    writeFileSync(recorded, '#!/bin/sh\n')
    chmodSync(recorded, 0o755)
    const fromRecorded = resolveUnit({ prefix, node: recorded, dshHome: '/tmp/dshhome' }, { platform: 'linux', home })
    expect(fromRecorded.spec.node).toBe(recorded)
    // The version-independent runtime link wins over the recorded path.
    const runtimeBin = join(prefix, 'runtime', 'node', 'current', 'bin')
    mkdirSync(runtimeBin, { recursive: true })
    writeFileSync(join(runtimeBin, 'node'), '#!/bin/sh\n')
    chmodSync(join(runtimeBin, 'node'), 0o755)
    const fromRuntime = resolveUnit({ prefix, node: recorded, dshHome: '/tmp/dshhome' }, { platform: 'linux', home })
    expect(fromRuntime.spec.node).toBe(join(runtimeBin, 'node'))
  })

  it('treats a blank recorded unit as absent and uses the default', () => {
    const home = tempDir()
    const linux = resolveUnit({ prefix: '/tmp/prefix', serviceUnit: '' }, { platform: 'linux', home })
    expect(linux.unit).toBe('dsh-web.service')
    expect(linux.path).toBe(join(home, '.config', 'systemd', 'user', 'dsh-web.service'))
    const darwin = resolveUnit({ prefix: '/tmp/prefix', serviceUnit: '   ' }, { platform: 'darwin', home })
    expect(darwin.unit).toBe('com.enpoi.dsh-web')
    expect(darwin.path).toBe(join(home, 'Library', 'LaunchAgents', 'com.enpoi.dsh-web.plist'))
    // A value that is not a plain file name must never escape the unit directory.
    const escaped = resolveUnit({ prefix: '/tmp/prefix', serviceUnit: '../evil' }, { platform: 'linux', home })
    expect(escaped.unit).toBe('dsh-web.service')
    expect(escaped.path).toBe(join(home, '.config', 'systemd', 'user', 'dsh-web.service'))
  })

  it('ignores a blank DSH_SERVICE_UNIT override', () => {
    const home = tempDir()
    process.env.DSH_SERVICE_UNIT = ''
    const linux = resolveUnit({ prefix: '/tmp/prefix' }, { platform: 'linux', home })
    expect(linux.unit).toBe('dsh-web.service')
    expect(linux.path).toBe(join(home, '.config', 'systemd', 'user', 'dsh-web.service'))
  })
})

describe('probeManagedService', () => {
  it('reports no managed install when the state file is absent', () => {
    expect(probeManagedService({ statePath: join(tempDir(), 'absent.json') })).toEqual({ kind: 'none' })
  })

  it('reports a missing unit when the recorded unit file is gone', () => {
    const home = tempDir()
    const statePath = join(tempDir(), 'install-state.json')
    writeFileSync(statePath, JSON.stringify({ prefix: join(home, 'prefix'), serviceUnit: 'dsh-web.service' }))
    expect(probeManagedService({ platform: 'linux', home, statePath }))
      .toEqual({ kind: 'missing', unit: 'dsh-web.service' })
  })

  it('reports the unit active or stopped from the platform manager', () => {
    const home = tempDir()
    const statePath = join(tempDir(), 'install-state.json')
    writeFileSync(statePath, JSON.stringify({ prefix: join(home, 'prefix'), serviceUnit: 'dsh-web.service' }))
    const unitPath = join(home, '.config', 'systemd', 'user', 'dsh-web.service')
    mkdirSync(dirname(unitPath), { recursive: true })
    writeFileSync(unitPath, '# Generated by dsh service install\n')
    expect(probeManagedService({ platform: 'linux', home, statePath, probeUnit: () => true }))
      .toEqual({ kind: 'active', unit: 'dsh-web.service' })
    expect(probeManagedService({ platform: 'linux', home, statePath, probeUnit: () => false }))
      .toEqual({ kind: 'stopped', unit: 'dsh-web.service' })
  })

  it('fails soft to unknown when the platform manager cannot answer', () => {
    const home = tempDir()
    const statePath = join(tempDir(), 'install-state.json')
    writeFileSync(statePath, JSON.stringify({ serviceUnit: 'com.example.dsh' }))
    const plistPath = join(home, 'Library', 'LaunchAgents', 'com.example.dsh.plist')
    mkdirSync(dirname(plistPath), { recursive: true })
    writeFileSync(plistPath, '<plist/>')
    let seenKind = ''
    const state = probeManagedService({
      platform: 'darwin',
      home,
      statePath,
      probeUnit: (kind) => {
        seenKind = kind
        return undefined
      },
    })
    expect(state).toEqual({ kind: 'unknown' })
    expect(seenKind).toBe('launchd')
  })
})

describe('runService', () => {
  it('prints usage for help', async () => {
    const out = sink()
    expect(await runService(['help'], { stdout: out, platform: 'linux' })).toBe(0)
    expect(out.text()).toContain('Usage: dsh service')
    expect(out.text()).toContain('install [--force] [--no-start]')
  })

  it('rejects unsupported platforms and missing installs', async () => {
    const err = sink()
    expect(await runService(['status'], { platform: 'win32', stderr: err })).toBe(1)
    expect(err.text()).toContain('WSL 2')
    const missing = sink()
    expect(await runService(['status'], { platform: 'linux', stderr: missing, statePath: join(tempDir(), 'absent.json') })).toBe(1)
    expect(missing.text()).toContain('no managed install')
  })

  it('refuses every service command on Windows, including help', async () => {
    const err = sink()
    expect(await runService(['help'], { platform: 'win32', stderr: err, stdout: sink() })).toBe(1)
    expect(err.text()).toContain('Windows is not supported')
    expect(err.text()).toContain('wsl --install')
  })

  it('installs, enables, starts, and records the unit on Linux', async () => {
    const home = tempDir()
    const statePath = join(home, 'install-state.json')
    writeFileSync(statePath, JSON.stringify({ prefix: '/tmp/prefix', node: '/usr/bin/node', binDir: '/tmp/prefix/bin', dshHome: '/tmp/dshhome', serviceInstall: false }))
    const { calls, run } = recorder()
    const out = sink()
    const code = await runService(['install'], { platform: 'linux', home, statePath, run, stdout: out })
    expect(code).toBe(0)
    const unitPath = join(home, '.config', 'systemd', 'user', 'dsh-web.service')
    expect(readFileSync(unitPath, 'utf8')).toContain('--foreground')
    const expected = ['--user daemon-reload', '--user enable dsh-web.service', '--user restart dsh-web.service']
    if (process.env.USER !== undefined) expected.splice(2, 0, `enable-linger ${process.env.USER}`)
    expect(calls.map(call => call.args.join(' '))).toEqual(expected)
    const recorded = JSON.parse(readFileSync(statePath, 'utf8'))
    expect(recorded.serviceUnit).toBe('dsh-web.service')
    // The installer's sticky serviceInstall flag survives the state rewrite.
    expect(recorded.serviceInstall).toBe(false)
  })

  it('installs without starting when --no-start is passed', async () => {
    const home = tempDir()
    const statePath = join(home, 'install-state.json')
    writeFileSync(statePath, '{}')
    const { calls, run } = recorder()
    await runService(['install', '--no-start'], { platform: 'linux', home, statePath, run, stdout: sink() })
    expect(calls.some(call => call.args[1] === 'restart')).toBe(false)
  })

  it('refuses to replace a foreign unit without --force', async () => {
    const home = tempDir()
    const statePath = join(home, 'install-state.json')
    writeFileSync(statePath, '{}')
    const unitPath = join(home, '.config', 'systemd', 'user', 'dsh-web.service')
    mkdirSync(join(home, '.config', 'systemd', 'user'), { recursive: true })
    writeFileSync(unitPath, '[Unit]\nDescription=hand-written dev unit\n')
    const err = sink()
    const { calls, run } = recorder()
    expect(await runService(['install'], { platform: 'linux', home, statePath, run, stderr: err })).toBe(1)
    expect(err.text()).toContain('--force')
    expect(calls).toEqual([])
    const out = sink()
    expect(await runService(['install', '--force'], { platform: 'linux', home, statePath, run, stdout: out })).toBe(0)
    expect(readFileSync(unitPath, 'utf8')).toContain('Generated by dsh service install')
    // The replaced foreign unit stays recoverable.
    expect(readFileSync(`${unitPath}.backup`, 'utf8')).toContain('hand-written dev unit')
    expect(out.text()).toContain(`${unitPath}.backup`)
  })

  it('installs when the state records a blank unit and the unit directory exists', async () => {
    const home = tempDir()
    const statePath = join(home, 'install-state.json')
    // The production failure: serviceUnit "" resolved the unit path to the
    // systemd user directory itself, so the install refused (and --force hit
    // EISDIR). The directory existing is the normal case.
    writeFileSync(statePath, JSON.stringify({ prefix: '/tmp/prefix', node: '/usr/bin/node', serviceUnit: '' }))
    mkdirSync(join(home, '.config', 'systemd', 'user'), { recursive: true })
    const { run } = recorder()
    expect(await runService(['install', '--no-start'], { platform: 'linux', home, statePath, run, stdout: sink() })).toBe(0)
    expect(readFileSync(join(home, '.config', 'systemd', 'user', 'dsh-web.service'), 'utf8')).toContain('Generated by dsh service install')
  })

  it('refuses to uninstall a foreign unit without --force', async () => {
    const home = tempDir()
    const statePath = join(home, 'install-state.json')
    writeFileSync(statePath, '{}')
    const unitPath = join(home, '.config', 'systemd', 'user', 'dsh-web.service')
    mkdirSync(join(home, '.config', 'systemd', 'user'), { recursive: true })
    writeFileSync(unitPath, '[Unit]\nDescription=hand-written dev unit\n')
    const { run, calls } = recorder()
    const err = sink()
    expect(await runService(['uninstall'], { platform: 'linux', home, statePath, run, stderr: err })).toBe(1)
    expect(err.text()).toContain('--force')
    expect(readFileSync(unitPath, 'utf8')).toContain('hand-written')
    expect(calls).toEqual([])
    expect(await runService(['uninstall', '--force'], { platform: 'linux', home, statePath, run, stdout: sink() })).toBe(0)
    expect(() => readFileSync(unitPath, 'utf8')).toThrow()
  })

  it('maps start/stop/restart/status/logs to systemctl and journalctl', async () => {
    const home = tempDir()
    const statePath = join(home, 'install-state.json')
    writeFileSync(statePath, '{}')
    const { calls, run } = recorder((_command, args) => (args[0] === '--user' && args[1] === 'status' ? 3 : 0))
    expect(await runService(['start'], { platform: 'linux', home, statePath, run, stdout: sink() })).toBe(0)
    expect(await runService(['stop'], { platform: 'linux', home, statePath, run, stdout: sink() })).toBe(0)
    expect(await runService(['restart'], { platform: 'linux', home, statePath, run, stdout: sink() })).toBe(0)
    expect(await runService(['status'], { platform: 'linux', home, statePath, run, stdout: sink() })).toBe(3)
    expect(await runService(['logs', '--lines', '5'], { platform: 'linux', home, statePath, run, stdout: sink() })).toBe(0)
    expect(calls.map(call => `${call.command} ${call.args.join(' ')}`)).toEqual([
      'systemctl --user start dsh-web.service',
      'systemctl --user stop dsh-web.service',
      'systemctl --user restart dsh-web.service',
      'systemctl --user status dsh-web.service --no-pager',
      'journalctl --user -u dsh-web.service -n 5 --no-pager',
    ])
  })

  it('bootstraps and kickstarts the launchd agent', async () => {
    const home = tempDir()
    const statePath = join(home, 'install-state.json')
    writeFileSync(statePath, JSON.stringify({ serviceUnit: 'com.example.dsh' }))
    let loaded = false
    const { calls, run } = recorder((command, args) => {
      if (command === 'launchctl' && args[0] === 'bootstrap') loaded = true
      if (command === 'launchctl' && args[0] === 'bootout') loaded = false
      return 0
    })
    const deps = {
      platform: 'darwin' as const,
      home,
      statePath,
      run,
      stdout: sink(),
      tailLog: () => 'tail',
      probeLoaded: () => loaded,
    }
    expect(await runService(['install'], deps)).toBe(0)
    const plist = join(home, 'Library', 'LaunchAgents', 'com.example.dsh.plist')
    expect(readFileSync(plist, 'utf8')).toContain('--foreground')
    expect(await runService(['stop'], deps)).toBe(0)
    expect(await runService(['start'], deps)).toBe(0)
    expect(await runService(['restart'], deps)).toBe(0)
    const executed = calls.map(call => `${call.command} ${call.args.join(' ')}`)
    const uid = typeof process.getuid === 'function' ? process.getuid() : 0
    expect(executed).toContain(`launchctl bootstrap gui/${uid} ${plist}`)
    expect(executed.filter(line => line.startsWith('launchctl bootstrap'))).toHaveLength(2)
    expect(executed).toContain(`launchctl kickstart -k gui/${uid}/com.example.dsh`)
  })

  it('degrades gracefully when launchd has no GUI domain (headless/SSH Mac)', async () => {
    const home = tempDir()
    const statePath = join(home, 'install-state.json')
    writeFileSync(statePath, JSON.stringify({ serviceUnit: 'com.example.dsh' }))
    const { run } = recorder((command, args) => (command === 'launchctl' && args[0] === 'bootstrap' ? 2 : 0))
    const err = sink()
    const code = await runService(['install'], {
      platform: 'darwin',
      home,
      statePath,
      run,
      stdout: sink(),
      stderr: err,
      probeLoaded: () => false,
      probeGuiDomain: () => false,
    })
    expect(code).toBe(2)
    const uid = typeof process.getuid === 'function' ? process.getuid() : 0
    const plist = join(home, 'Library', 'LaunchAgents', 'com.example.dsh.plist')
    expect(err.text()).toContain('headless or SSH-only Mac')
    expect(err.text()).toContain(`launchctl bootstrap gui/${uid} ${plist}`)
    // The unit and its record stay behind: the agent loads at the next desktop login.
    expect(readFileSync(plist, 'utf8')).toContain('--foreground')
    expect(JSON.parse(readFileSync(statePath, 'utf8')).serviceUnit).toBe('com.example.dsh')
  })

  it('reports a launchctl bootstrap failure and the retry command', async () => {
    const home = tempDir()
    const statePath = join(home, 'install-state.json')
    writeFileSync(statePath, '{}')
    const { run } = recorder((command, args) => (command === 'launchctl' && args[0] === 'bootstrap' ? 5 : 0))
    const err = sink()
    const code = await runService(['install'], {
      platform: 'darwin',
      home,
      statePath,
      run,
      stdout: sink(),
      stderr: err,
      probeLoaded: () => false,
      probeGuiDomain: () => true,
    })
    expect(code).toBe(5)
    expect(err.text()).toContain('launchctl bootstrap failed (exit 5)')
    const uid = typeof process.getuid === 'function' ? process.getuid() : 0
    expect(err.text()).toContain(`launchctl bootstrap gui/${uid} `)
  })

  it('explains a headless start attempt instead of failing silently', async () => {
    const home = tempDir()
    const statePath = join(home, 'install-state.json')
    writeFileSync(statePath, '{}')
    const { run } = recorder((command, args) => (command === 'launchctl' && args[0] === 'bootstrap' ? 3 : 0))
    const err = sink()
    const code = await runService(['start'], {
      platform: 'darwin',
      home,
      statePath,
      run,
      stderr: err,
      probeLoaded: () => false,
      probeGuiDomain: () => false,
    })
    expect(code).toBe(3)
    expect(err.text()).toContain('headless or SSH-only Mac')
  })

  it('leaves a loaded launchd agent untouched when --no-start is passed', async () => {
    const home = tempDir()
    const statePath = join(home, 'install-state.json')
    writeFileSync(statePath, JSON.stringify({ serviceUnit: 'com.example.dsh' }))
    const { calls, run } = recorder()
    const code = await runService(['install', '--no-start'], {
      platform: 'darwin',
      home,
      statePath,
      run,
      stdout: sink(),
      probeLoaded: () => true,
    })
    expect(code).toBe(0)
    expect(calls).toEqual([])
  })

  it('does not bounce a loaded launchd agent whose plist is unchanged', async () => {
    const home = tempDir()
    const statePath = join(home, 'install-state.json')
    const state = { serviceUnit: 'com.example.dsh', prefix: join(home, 'prefix'), binDir: join(home, 'bin'), dshHome: join(home, 'dsh') }
    writeFileSync(statePath, JSON.stringify(state))
    const unit = resolveUnit(state, { platform: 'darwin', home })
    mkdirSync(dirname(unit.path), { recursive: true })
    writeFileSync(unit.path, unit.content)
    const { calls, run } = recorder()
    const out = sink()
    const code = await runService(['install'], { platform: 'darwin', home, statePath, run, stdout: out, probeLoaded: () => true })
    expect(code).toBe(0)
    expect(calls).toEqual([])
    expect(out.text()).toContain('installed and started')
  })

  it('restores the previous plist when a loaded agent fails to rebootstrap', async () => {
    const home = tempDir()
    const statePath = join(home, 'install-state.json')
    writeFileSync(statePath, JSON.stringify({ serviceUnit: 'com.example.dsh' }))
    const plistPath = join(home, 'Library', 'LaunchAgents', 'com.example.dsh.plist')
    mkdirSync(dirname(plistPath), { recursive: true })
    const previous = '<!-- Generated by dsh service install -->\nOLD DEFINITION\n'
    writeFileSync(plistPath, previous)
    let bootstraps = 0
    const { calls, run } = recorder((command, args) => {
      if (command === 'launchctl' && args[0] === 'bootstrap') {
        bootstraps += 1
        return bootstraps === 1 ? 5 : 0
      }
      return 0
    })
    const err = sink()
    const code = await runService(['install'], {
      platform: 'darwin',
      home,
      statePath,
      run,
      stdout: sink(),
      stderr: err,
      probeLoaded: () => true,
      probeGuiDomain: () => true,
    })
    expect(code).toBe(5)
    expect(err.text()).toContain('restored and reloaded the previous unit')
    expect(readFileSync(plistPath, 'utf8')).toBe(previous)
    expect(calls.filter(call => call.args[0] === 'bootstrap')).toHaveLength(2)
  })

  it('warns when systemd cannot enable the unit but still starts it', async () => {
    const home = tempDir()
    const statePath = join(home, 'install-state.json')
    writeFileSync(statePath, '{}')
    const { calls, run } = recorder((_command, args) => (args[1] === 'enable' ? 1 : 0))
    const err = sink()
    const code = await runService(['install'], { platform: 'linux', home, statePath, run, stdout: sink(), stderr: err })
    expect(code).toBe(0)
    expect(err.text()).toContain('will not start at login')
    expect(calls.some(call => call.args[1] === 'restart')).toBe(true)
  })

  it.skipIf(typeof process.getuid === 'function' && process.getuid() === 0)(
    'warns when the install state cannot record the unit',
    async () => {
      const home = tempDir()
      const statePath = join(home, 'install-state.json')
      writeFileSync(statePath, '{}')
      chmodSync(statePath, 0o444)
      const err = sink()
      const { run } = recorder()
      const code = await runService(['install', '--no-start'], { platform: 'linux', home, statePath, run, stdout: sink(), stderr: err })
      expect(code).toBe(0)
      expect(err.text()).toContain('could not record')
    },
  )

  it('removes the unit and clears the record on uninstall', async () => {
    const home = tempDir()
    const statePath = join(home, 'install-state.json')
    writeFileSync(statePath, '{}')
    const { run } = recorder()
    await runService(['install', '--no-start'], { platform: 'linux', home, statePath, run, stdout: sink() })
    const unitPath = join(home, '.config', 'systemd', 'user', 'dsh-web.service')
    expect(readFileSync(unitPath, 'utf8')).toContain('Generated by')
    expect(await runService(['uninstall'], { platform: 'linux', home, statePath, run, stdout: sink() })).toBe(0)
    expect(() => readFileSync(unitPath, 'utf8')).toThrow()
    expect(JSON.parse(readFileSync(statePath, 'utf8')).serviceUnit).toBeNull()
  })

  it('prints the recorded URL on status when the instance state is live', async () => {
    const home = tempDir()
    const dshHome = tempDir()
    process.env.DSH_HOME = dshHome
    const statePath = join(home, 'install-state.json')
    writeFileSync(statePath, '{}')
    mkdirSync(join(dshHome, 'state'), { recursive: true })
    writeFileSync(join(dshHome, 'state', 'web-url.json'), JSON.stringify({ url: 'http://127.0.0.1:3080/?token=t', host: '127.0.0.1', port: 3080, pid: process.pid, startedAt: 'x' }))
    const out = sink()
    const { run } = recorder()
    await runService(['status'], { platform: 'linux', home, statePath, run, stdout: out })
    expect(out.text()).toContain('dsh web: http://127.0.0.1:3080/?token=t')
  })
})
