/**
 * The shared model-capability id-heuristic table, generated from
 * profile/web/packages/enpoi-provider-sync/model-capability-hints.json.
 *
 * GENERATED by profile/web/packages/enpoi-provider-sync/scripts/write-client-mirror.mjs
 * — do not edit by hand; run the script after a table change. The table is
 * hints only: the sync persists a hinted capability under `capabilityHints`,
 * never as a disclosed fact.
 */

/** The shipped id-heuristic operand table. Every list holds lowercase id substrings. */
export interface ModelCapabilityHints {
  readonly reasoning: readonly string[]
  readonly image: readonly string[]
  readonly audio: readonly string[]
  readonly video: readonly string[]
  readonly files: readonly string[]
  readonly toolsExclude: readonly string[]
}

/** The generated mirror of the shipped `model-capability-hints.json`. */
export const MODEL_CAPABILITY_HINTS: ModelCapabilityHints = {
  reasoning: [
    'astra',
    'deepseek-r',
    'deepseek-v4',
    'fable-5',
    'flash-tiered',
    'glm-4.7',
    'glm-5',
    'gpt-5',
    'grok-4',
    'hy3',
    'hy4',
    'k3',
    'kimi-k2',
    'longcat',
    'luna',
    'm2.7',
    'm3',
    'mimo-v2',
    'muse-spark',
    'o1',
    'o3',
    'o4',
    'omen-alpha',
    'opus-4-6',
    'opus-4-7',
    'opus-4-8',
    'opus-5',
    'pro-agent',
    'pro-high',
    'qwen3.8',
    'r1',
    'reason',
    'sol',
    'terra',
    'think',
  ],
  image: [
    'claude',
    'gemini',
    'glm-4v',
    'glm-5v',
    'gpt-4',
    'gpt-5',
    'grok-2',
    'internvl',
    'k3',
    'llava',
    'luna',
    'mimo',
    'minimax',
    'pixtral',
    'qwen-vl',
    'qwen2.5-vl',
    'qwen3-vl',
    'qwen3.8-vl',
    'vision',
    'vl',
  ],
  audio: [
    'audio',
    'gemini-1.5',
    'gemini-2.5',
    'gemini-3.6',
    'gemini-3.7',
    'gpt-4o-audio',
    'gpt-4o-realtime',
    'minimax-m2.5',
    'minimax-m2.7',
    'minimax-m3',
    'mimo-v2.5',
    'mimo-v2.6',
    'muse-spark-1.2',
    'muse-spark-1.3',
    'voice',
    'whisper',
  ],
  video: [
    'gemini-1.5',
    'gemini-2.5',
    'gemini-3.1',
    'gemini-3.6',
    'gemini-3.7',
    'minimax-m2.7',
    'minimax-m3',
    'qwen-vl',
    'qwen2.5-vl',
    'space-bunny',
  ],
  files: [
    'claude',
    'document',
    'gemini',
    'gpt-4',
    'gpt-5',
    'luna',
    'pdf',
  ],
  toolsExclude: [
    'dall-e',
    'embed',
    'flux',
    'rerank',
    'reward',
    'text-01',
  ],
}
