// Generated by packages/client/ui-settings-models/scripts/gen-provider-presets.mjs
// Source: models.dev cache ~/.cache/opencode/models.json; pi-ai bundled baseUrl catalog
// Regenerate with: node packages/client/ui-settings-models/scripts/gen-provider-presets.mjs
export default [
  {
    'id': '302ai',
    'name': '302.AI',
    'env': [
      '302AI_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.302.ai/v1',
    'doc': 'https://doc.302.ai',
  },
  {
    'id': 'abacus',
    'name': 'Abacus',
    'env': [
      'ABACUS_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://routellm.abacus.ai/v1',
    'doc': 'https://abacus.ai/help/api',
  },
  {
    'id': 'abliteration-ai',
    'name': 'abliteration.ai',
    'env': [
      'ABLIT_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.abliteration.ai/v1',
    'doc': 'https://docs.abliteration.ai/models',
  },
  {
    'id': 'above',
    'name': 'above.dev',
    'env': [
      'ABOVE_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.above.dev/v1',
    'doc': 'https://above.dev/docs',
  },
  {
    'id': 'agentrouter',
    'name': 'AgentRouter',
    'env': [
      'AGENTROUTER_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://agentrouter.org/v1',
    'doc': 'https://agentrouter.org/docs/opencode.html',
  },
  {
    'id': 'agnes',
    'name': 'Agnes AI',
    'env': [
      'AGNES_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://apihub.agnes-ai.com/v1',
    'doc': 'https://agnes-ai.com/doc',
  },
  {
    'id': 'ai-router',
    'name': 'AI-ROUTER',
    'env': [
      'AI_ROUTER_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.ai-router.dev/v1',
    'doc': 'https://ai-router.dev/openai-compatible-api-gateway/',
  },
  {
    'id': 'aiand',
    'name': 'ai&',
    'env': [
      'AIAND_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.aiand.com/v1',
    'doc': 'https://docs.aiand.com/',
  },
  {
    'id': 'aihubmix',
    'name': 'AIHubMix',
    'env': [
      'AIHUBMIX_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': '',
    'doc': 'https://docs.aihubmix.com',
  },
  {
    'id': 'aixy',
    'name': 'Aixy',
    'env': [
      'AIXY_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.aixy-gateway.com/v1',
    'doc': 'https://docs.aixy-gateway.com/integrations/overview',
  },
  {
    'id': 'aki-io',
    'name': 'AKI.IO',
    'env': [
      'AKI_IO_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://aki.io/v1',
    'doc': 'https://aki.io/docs/',
  },
  {
    'id': 'alibaba',
    'name': 'Alibaba',
    'env': [
      'DASHSCOPE_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://dashscope-intl.aliyuncs.com/compatible-mode/v1',
    'doc': 'https://www.alibabacloud.com/help/en/model-studio/models',
  },
  {
    'id': 'alibaba-cn',
    'name': 'Alibaba (China)',
    'env': [
      'DASHSCOPE_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    'doc': 'https://www.alibabacloud.com/help/en/model-studio/models',
  },
  {
    'id': 'alibaba-coding-plan',
    'name': 'Alibaba Coding Plan',
    'env': [
      'ALIBABA_CODING_PLAN_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://coding-intl.dashscope.aliyuncs.com/v1',
    'doc': 'https://www.alibabacloud.com/help/en/model-studio/coding-plan',
  },
  {
    'id': 'alibaba-coding-plan-cn',
    'name': 'Alibaba Coding Plan (China)',
    'env': [
      'ALIBABA_CODING_PLAN_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://coding.dashscope.aliyuncs.com/v1',
    'doc': 'https://help.aliyun.com/zh/model-studio/coding-plan',
  },
  {
    'id': 'alibaba-token-plan',
    'name': 'Alibaba Token Plan',
    'env': [
      'ALIBABA_TOKEN_PLAN_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://token-plan.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1',
    'doc': 'https://www.alibabacloud.com/help/en/model-studio/token-plan-overview',
  },
  {
    'id': 'alibaba-token-plan-cn',
    'name': 'Alibaba Token Plan (China)',
    'env': [
      'ALIBABA_TOKEN_PLAN_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1',
    'doc': 'https://www.alibabacloud.com/help/zh/model-studio/token-plan-overview',
  },
  {
    'id': 'amazon-bedrock',
    'name': 'Amazon Bedrock',
    'env': [
      'AWS_ACCESS_KEY_ID',
      'AWS_SECRET_ACCESS_KEY',
      'AWS_REGION',
      'AWS_BEARER_TOKEN_BEDROCK',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://bedrock-runtime.us-east-1.amazonaws.com',
    'doc': 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
  },
  {
    'id': 'ambient',
    'name': 'Ambient',
    'env': [
      'AMBIENT_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.ambient.xyz/v1',
    'doc': 'https://ambient.xyz',
  },
  {
    'id': 'amd',
    'name': 'AMD',
    'env': [
      'AMD_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://developer.amd.com.cn/radeon/api/v1',
    'doc': 'https://developer.amd.com.cn/radeon/tokenfactory',
  },
  {
    'id': 'anthropic',
    'name': 'Anthropic',
    'env': [
      'ANTHROPIC_API_KEY',
    ],
    'protocol': 'anthropic-messages',
    'baseURL': 'https://api.anthropic.com',
    'doc': 'https://docs.anthropic.com/en/docs/about-claude/models',
  },
  {
    'id': 'anyapi',
    'name': 'AnyAPI',
    'env': [
      'ANYAPI_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.anyapi.ai/v1',
    'doc': 'https://docs.anyapi.ai',
  },
  {
    'id': 'arcee',
    'name': 'Arcee',
    'env': [
      'ARCEE_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.arcee.ai/api/v1',
    'doc': 'https://docs.arcee.ai',
  },
  {
    'id': 'atomic-chat',
    'name': 'Atomic Chat',
    'env': [
      'ATOMIC_CHAT_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'http://127.0.0.1:1337/v1',
    'doc': 'https://atomic.chat',
  },
  {
    'id': 'auriko',
    'name': 'Auriko',
    'env': [
      'AURIKO_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.auriko.ai/v1',
    'doc': 'https://docs.auriko.ai',
  },
  {
    'id': 'azure',
    'name': 'Azure',
    'env': [
      'AZURE_RESOURCE_NAME',
      'AZURE_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': '',
    'doc': 'https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models',
  },
  {
    'id': 'azure-cognitive-services',
    'name': 'Azure Cognitive Services',
    'env': [
      'AZURE_COGNITIVE_SERVICES_RESOURCE_NAME',
      'AZURE_COGNITIVE_SERVICES_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': '',
    'doc': 'https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models',
  },
  {
    'id': 'bailing',
    'name': 'Bailing',
    'env': [
      'BAILING_API_TOKEN',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.tbox.cn/api/llm/v1/chat/completions',
    'doc': 'https://alipaytbox.yuque.com/sxs0ba/ling/intro',
  },
  {
    'id': 'baseten',
    'name': 'Baseten',
    'env': [
      'BASETEN_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://inference.baseten.co/v1',
    'doc': 'https://docs.baseten.co/inference/model-apis/overview',
  },
  {
    'id': 'berget',
    'name': 'Berget.AI',
    'env': [
      'BERGET_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.berget.ai/v1',
    'doc': 'https://api.berget.ai',
  },
  {
    'id': 'blueclaw',
    'name': 'Blue Claw',
    'env': [
      'BLUECLAW_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://openai.blueclaw.network/v1',
    'doc': 'https://blueclaw.network',
  },
  {
    'id': 'bothub',
    'name': 'Bothub',
    'env': [
      'BOTHUB_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://openai.bothub.ru/v1',
    'doc': 'https://bothub.ru/models',
  },
  {
    'id': 'cerebras',
    'name': 'Cerebras',
    'env': [
      'CEREBRAS_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.cerebras.ai/v1',
    'doc': 'https://inference-docs.cerebras.ai/models/overview',
  },
  {
    'id': 'hyper',
    'name': 'Charm Hyper',
    'env': [
      'HYPER_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://hyper.charm.land/v1',
    'doc': 'https://hyper.charm.land',
  },
  {
    'id': 'chutes',
    'name': 'Chutes',
    'env': [
      'CHUTES_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://llm.chutes.ai/v1',
    'doc': 'https://llm.chutes.ai/v1/models',
  },
  {
    'id': 'clarifai',
    'name': 'Clarifai',
    'env': [
      'CLARIFAI_PAT',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.clarifai.com/v2/ext/openai/v1',
    'doc': 'https://docs.clarifai.com/compute/inference/',
  },
  {
    'id': 'claudinio',
    'name': 'Claudinio',
    'env': [
      'CLAUDINIO_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.claudin.io/v1',
    'doc': 'https://claudin.io',
  },
  {
    'id': 'cline-pass',
    'name': 'ClinePass',
    'env': [
      'CLINE_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.cline.bot/api/v1',
    'doc': 'https://docs.cline.bot/getting-started/clinepass',
  },
  {
    'id': 'cloudferro-sherlock',
    'name': 'CloudFerro Sherlock',
    'env': [
      'CLOUDFERRO_SHERLOCK_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api-sherlock.cloudferro.com/openai/v1/',
    'doc': 'https://docs.sherlock.cloudferro.com/',
  },
  {
    'id': 'cloudflare-ai-gateway',
    'name': 'Cloudflare AI Gateway',
    'env': [
      'CLOUDFLARE_API_TOKEN',
      'CLOUDFLARE_ACCOUNT_ID',
      'CLOUDFLARE_GATEWAY_ID',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://gateway.ai.cloudflare.com/v1/{CLOUDFLARE_ACCOUNT_ID}/{CLOUDFLARE_GATEWAY_ID}/anthropic',
    'doc': 'https://developers.cloudflare.com/ai-gateway/',
  },
  {
    'id': 'cloudflare-workers-ai',
    'name': 'Cloudflare Workers AI',
    'env': [
      'CLOUDFLARE_ACCOUNT_ID',
      'CLOUDFLARE_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.cloudflare.com/client/v4/accounts/{env:CLOUDFLARE_ACCOUNT_ID}/ai/v1',
    'doc': 'https://developers.cloudflare.com/workers-ai/models/',
  },
  {
    'id': 'cohere',
    'name': 'Cohere',
    'env': [
      'COHERE_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': '',
    'doc': 'https://docs.cohere.com/docs/models',
  },
  {
    'id': 'coralbricks',
    'name': 'CoralBricks',
    'env': [
      'CORAL_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://inference.coralbricks.ai/v1',
    'doc': 'https://www.coralbricks.ai/docs',
  },
  {
    'id': 'cortecs',
    'name': 'Cortecs',
    'env': [
      'CORTECS_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.cortecs.ai/v1',
    'doc': 'https://api.cortecs.ai/v1/models',
  },
  {
    'id': 'crof',
    'name': 'CrofAI',
    'env': [
      'CROF_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://crof.ai/v1',
    'doc': 'https://crof.ai/docs',
  },
  {
    'id': 'crossmodel',
    'name': 'CrossModel',
    'env': [
      'CROSSMODEL_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.crossmodel.ai/v1',
    'doc': 'https://www.crossmodel.ai/docs',
  },
  {
    'id': 'crusoe',
    'name': 'Crusoe',
    'env': [
      'CRUSOE_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.inference.crusoecloud.com/v1',
    'doc': 'https://docs.crusoecloud.com/managed-inference/overview',
  },
  {
    'id': 'drun',
    'name': 'D.Run (China)',
    'env': [
      'DRUN_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://chat.d.run/v1',
    'doc': 'https://www.d.run',
  },
  {
    'id': 'daoxe',
    'name': 'DaoXE',
    'env': [
      'DAOXE_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://daoxe.com/v1',
    'doc': 'https://daoxe.com/pricing',
  },
  {
    'id': 'databricks',
    'name': 'Databricks',
    'env': [
      'DATABRICKS_HOST',
      'DATABRICKS_TOKEN',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://{env:DATABRICKS_HOST}/ai-gateway/mlflow/v1',
    'doc': 'https://docs.databricks.com/aws/en/machine-learning/foundation-models/',
  },
  {
    'id': 'deepinfra',
    'name': 'Deep Infra',
    'env': [
      'DEEPINFRA_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': '',
    'doc': 'https://deepinfra.com/models',
  },
  {
    'id': 'deepseek',
    'name': 'DeepSeek',
    'env': [
      'DEEPSEEK_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.deepseek.com',
    'doc': 'https://api-docs.deepseek.com/quick_start/pricing',
  },
  {
    'id': 'llmgateway',
    'name': 'DevPass (LLM Gateway)',
    'env': [
      'LLMGATEWAY_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.llmgateway.io/v1',
    'doc': 'https://llmgateway.io/docs',
  },
  {
    'id': 'digitalocean',
    'name': 'DigitalOcean',
    'env': [
      'DIGITALOCEAN_ACCESS_TOKEN',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://inference.do-ai.run/v1',
    'doc': 'https://docs.digitalocean.com/products/gradient-ai-platform/details/models/',
  },
  {
    'id': 'dinference',
    'name': 'DInference',
    'env': [
      'DINFERENCE_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.dinference.com/v1',
    'doc': 'https://dinference.com',
  },
  {
    'id': 'ebcloud',
    'name': 'EBCloud',
    'env': [
      'EBCLOUD_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://maas-api.ebcloud.com/v1',
    'doc': 'https://docs.ebtech.com/ai/model-api.html',
  },
  {
    'id': 'echo',
    'name': 'Echo',
    'env': [
      'ECHO_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://echo.tracerml.ai/v1',
    'doc': 'https://echo.tracerml.ai/docs/api',
  },
  {
    'id': 'edenai',
    'name': 'Eden AI',
    'env': [
      'EDENAI_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.edenai.run/v3',
    'doc': 'https://docs.edenai.co',
  },
  {
    'id': 'empiriolabs',
    'name': 'EmpirioLabs AI',
    'env': [
      'EMPIRIOLABS_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.empiriolabs.ai/v1',
    'doc': 'https://docs.empiriolabs.ai',
  },
  {
    'id': 'evroc',
    'name': 'evroc',
    'env': [
      'EVROC_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://models.think.evroc.com/v1',
    'doc': 'https://docs.evroc.com/products/think/overview.html',
  },
  {
    'id': 'fastrouter',
    'name': 'FastRouter',
    'env': [
      'FASTROUTER_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://go.fastrouter.ai/api/v1',
    'doc': 'https://fastrouter.ai/models',
  },
  {
    'id': 'fireworks-ai',
    'name': 'Fireworks AI',
    'env': [
      'FIREWORKS_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.fireworks.ai/inference/v1/',
    'doc': 'https://fireworks.ai/docs/',
  },
  {
    'id': 'freemodel',
    'name': 'FreeModel',
    'env': [
      'FREEMODEL_API_KEY',
    ],
    'protocol': 'anthropic-messages',
    'baseURL': 'https://cc.freemodel.dev/v1',
    'doc': 'https://freemodel.dev',
  },
  {
    'id': 'friendli',
    'name': 'Friendli',
    'env': [
      'FRIENDLI_TOKEN',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.friendli.ai/serverless/v1',
    'doc': 'https://friendli.ai/docs/guides/serverless_endpoints/introduction',
  },
  {
    'id': 'frogbot',
    'name': 'FrogBot',
    'env': [
      'FROGBOT_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://app.frogbot.ai/api/v1',
    'doc': 'https://docs.frogbot.ai',
  },
  {
    'id': 'github-copilot',
    'name': 'GitHub Copilot',
    'env': [
      'GITHUB_TOKEN',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.githubcopilot.com',
    'doc': 'https://docs.github.com/en/copilot',
  },
  {
    'id': 'gitlab',
    'name': 'GitLab Duo',
    'env': [
      'GITLAB_TOKEN',
    ],
    'protocol': 'openai-completions',
    'baseURL': '',
    'doc': 'https://docs.gitlab.com/user/duo_agent_platform/',
  },
  {
    'id': 'gmicloud',
    'name': 'GMI Cloud',
    'env': [
      'GMICLOUD_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.gmi-serving.com/v1',
    'doc': 'https://docs.gmicloud.ai/inference-engine/api-reference/llm-api-reference',
  },
  {
    'id': 'google',
    'name': 'Google',
    'env': [
      'GOOGLE_API_KEY',
      'GOOGLE_GENERATIVE_AI_API_KEY',
      'GEMINI_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://generativelanguage.googleapis.com/v1beta',
    'doc': 'https://ai.google.dev/gemini-api/docs/models',
  },
  {
    'id': 'greenpt',
    'name': 'GreenPT',
    'env': [
      'GREENPT_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.greenpt.ai/v1',
    'doc': 'https://docs.greenpt.ai',
  },
  {
    'id': 'groq',
    'name': 'Groq',
    'env': [
      'GROQ_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.groq.com/openai/v1',
    'doc': 'https://console.groq.com/docs/models',
  },
  {
    'id': 'helicone',
    'name': 'Helicone',
    'env': [
      'HELICONE_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://ai-gateway.helicone.ai/v1',
    'doc': 'https://helicone.ai/models',
  },
  {
    'id': 'hetzner',
    'name': 'Hetzner',
    'env': [
      'HETZNER_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://inference.hetzner.com/api/v1',
    'doc': 'https://experiments.hetzner.com/docs/inference',
  },
  {
    'id': 'hpc-ai',
    'name': 'HPC-AI',
    'env': [
      'HPC_AI_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.hpc-ai.com/inference/v1',
    'doc': 'https://www.hpc-ai.com/doc/docs/quickstart/',
  },
  {
    'id': 'huggingface',
    'name': 'Hugging Face',
    'env': [
      'HF_TOKEN',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://router.huggingface.co/v1',
    'doc': 'https://huggingface.co/docs/inference-providers',
  },
  {
    'id': 'iflowcn',
    'name': 'iFlow',
    'env': [
      'IFLOW_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://apis.iflow.cn/v1',
    'doc': 'https://platform.iflow.cn/en/docs',
  },
  {
    'id': 'impossibl',
    'name': 'Impossibl',
    'env': [
      'IMPOSSIBL_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.impossibl.com/v1',
    'doc': 'https://impossibl.com/docs/models',
  },
  {
    'id': 'inception',
    'name': 'Inception',
    'env': [
      'INCEPTION_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.inceptionlabs.ai/v1/',
    'doc': 'https://platform.inceptionlabs.ai/docs',
  },
  {
    'id': 'inceptron',
    'name': 'Inceptron',
    'env': [
      'INCEPTRON_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.inceptron.io/v1',
    'doc': 'https://docs.inceptron.io',
  },
  {
    'id': 'inference',
    'name': 'Inference',
    'env': [
      'INFERENCE_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://inference.net/v1',
    'doc': 'https://inference.net/models',
  },
  {
    'id': 'inferx',
    'name': 'InferX',
    'env': [
      'INFERX_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://model.inferx.net/endpoints/v1',
    'doc': 'https://model.inferx.net/endpoints',
  },
  {
    'id': 'infomaniak',
    'name': 'Infomaniak',
    'env': [
      'INFOMANIAK_API_KEY',
      'INFOMANIAK_PRODUCT_ID',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.infomaniak.com/2/ai/{env:INFOMANIAK_PRODUCT_ID}/openai/v1',
    'doc': 'https://www.infomaniak.com/en/hosting/ai-services/open-source-models',
  },
  {
    'id': 'io-net',
    'name': 'IO.NET',
    'env': [
      'IOINTELLIGENCE_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.intelligence.io.solutions/api/v1',
    'doc': 'https://io.net/docs/guides/intelligence/io-intelligence',
  },
  {
    'id': 'iteracompute',
    'name': 'IteraCompute',
    'env': [
      'ITERACOMPUTE_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.iteracompute.com/v1',
    'doc': 'https://iteracompute.com/docs.html',
  },
  {
    'id': 'jalapeno',
    'name': 'Jalapeno Cloud',
    'env': [
      'JALAPENO_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.jalapeno-cloud.ai/v1',
    'doc': 'https://www.jalapeno-cloud.ai/docs/',
  },
  {
    'id': 'jiekou',
    'name': 'Jiekou.AI',
    'env': [
      'JIEKOU_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.jiekou.ai/openai',
    'doc': 'https://docs.jiekou.ai/docs/support/quickstart?utm_source=github_models.dev',
  },
  {
    'id': 'kenari',
    'name': 'Kenari',
    'env': [
      'KENARI_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://kenari.id/v1',
    'doc': 'https://kenari.id/docs',
  },
  {
    'id': 'kilo',
    'name': 'Kilo Gateway',
    'env': [
      'KILO_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.kilo.ai/api/gateway',
    'doc': 'https://kilo.ai',
  },
  {
    'id': 'kimi-for-coding',
    'name': 'Kimi For Coding',
    'env': [
      'KIMI_API_KEY',
    ],
    'protocol': 'anthropic-messages',
    'baseURL': 'https://api.kimi.com/coding/v1',
    'doc': 'https://www.kimi.com/code/docs/en/third-party-tools/other-coding-agents.html',
  },
  {
    'id': 'klokintegration',
    'name': 'klokintegration.se',
    'env': [
      'KLOKINTEGRATION_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api-gw.klok.ipaas.se/proxy/kloker-key/v1',
    'doc': 'https://klokintegration.se/docs/ai-api',
  },
  {
    'id': 'kosmik',
    'name': 'Kosmik Compute',
    'env': [
      'KOSMIK_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.koscompute.com/v1',
    'doc': 'https://api.koscompute.com/docs/',
  },
  {
    'id': 'kuae-cloud-coding-plan',
    'name': 'KUAE Cloud Coding Plan',
    'env': [
      'KUAE_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://coding-plan-endpoint.kuaecloud.net/v1',
    'doc': 'https://docs.mthreads.com/kuaecloud/kuaecloud-doc-online/coding_plan/',
  },
  {
    'id': 'lilac',
    'name': 'Lilac',
    'env': [
      'LILAC_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.getlilac.com/v1',
    'doc': 'https://docs.getlilac.com/inference/models',
  },
  {
    'id': 'llama',
    'name': 'Llama',
    'env': [
      'LLAMA_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.llama.com/compat/v1/',
    'doc': 'https://llama.developer.meta.com/docs/models',
  },
  {
    'id': 'llmgateway-providers',
    'name': 'LLM Gateway',
    'env': [
      'LLMGATEWAY_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.llmgateway.io/v1',
    'doc': 'https://llmgateway.io/docs',
  },
  {
    'id': 'llmtech',
    'name': 'LLM Tech',
    'env': [
      'LLMTECH_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.llmtech.eu/v1',
    'doc': 'https://llmtech.eu/models/qwen3.8-27b',
  },
  {
    'id': 'llmtr',
    'name': 'LLMTR',
    'env': [
      'LLMTR_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://llmtr.com/v1',
    'doc': 'https://llmtr.com/docs',
  },
  {
    'id': 'lmstudio',
    'name': 'LMStudio',
    'env': [
      'LMSTUDIO_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'http://127.0.0.1:1234/v1',
    'doc': 'https://lmstudio.ai/models',
  },
  {
    'id': 'longcat',
    'name': 'LongCat',
    'env': [
      'LONGCAT_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.longcat.chat/openai',
    'doc': 'https://longcat.chat/platform/docs/',
  },
  {
    'id': 'lucidquery',
    'name': 'LucidQuery',
    'env': [
      'LUCIDQUERY_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.lucidquery.com/v1',
    'doc': 'https://lucidquery.com/docs',
  },
  {
    'id': 'lynkr',
    'name': 'Lynkr',
    'env': [
      'LYNKR_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'http://127.0.0.1:8081/v1',
    'doc': 'https://github.com/Fast-Editor/Lynkr',
  },
  {
    'id': 'meganova',
    'name': 'Meganova',
    'env': [
      'MEGANOVA_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.meganova.ai/v1',
    'doc': 'https://docs.meganova.ai',
  },
  {
    'id': 'merge-gateway',
    'name': 'Merge Gateway',
    'env': [
      'MERGE_GATEWAY_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api-gateway.merge.dev/v1/ai-sdk',
    'doc': 'https://docs.merge.dev/merge-gateway',
  },
  {
    'id': 'meta',
    'name': 'Meta',
    'env': [
      'META_MODEL_API_KEY',
    ],
    'protocol': 'openai-responses',
    'baseURL': 'https://api.meta.ai/v1',
    'doc': 'https://dev.meta.ai/docs',
  },
  {
    'id': 'minimax',
    'name': 'MiniMax (minimax.io)',
    'env': [
      'MINIMAX_API_KEY',
    ],
    'protocol': 'anthropic-messages',
    'baseURL': 'https://api.minimax.io/anthropic/v1',
    'doc': 'https://platform.minimax.io/docs/guides/quickstart',
  },
  {
    'id': 'minimax-cn',
    'name': 'MiniMax (minimaxi.com)',
    'env': [
      'MINIMAX_API_KEY',
    ],
    'protocol': 'anthropic-messages',
    'baseURL': 'https://api.minimaxi.com/anthropic/v1',
    'doc': 'https://platform.minimaxi.com/docs/guides/quickstart',
  },
  {
    'id': 'minimax-coding-plan',
    'name': 'MiniMax Token Plan (minimax.io)',
    'env': [
      'MINIMAX_API_KEY',
    ],
    'protocol': 'anthropic-messages',
    'baseURL': 'https://api.minimax.io/anthropic/v1',
    'doc': 'https://platform.minimax.io/docs/token-plan/intro',
  },
  {
    'id': 'minimax-cn-coding-plan',
    'name': 'MiniMax Token Plan (minimaxi.com)',
    'env': [
      'MINIMAX_API_KEY',
    ],
    'protocol': 'anthropic-messages',
    'baseURL': 'https://api.minimaxi.com/anthropic/v1',
    'doc': 'https://platform.minimaxi.com/docs/token-plan/intro',
  },
  {
    'id': 'mistral',
    'name': 'Mistral',
    'env': [
      'MISTRAL_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.mistral.ai',
    'doc': 'https://docs.mistral.ai/getting-started/models/',
  },
  {
    'id': 'mixlayer',
    'name': 'Mixlayer',
    'env': [
      'MIXLAYER_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://models.mixlayer.ai/v1',
    'doc': 'https://docs.mixlayer.com',
  },
  {
    'id': 'moark',
    'name': 'Moark',
    'env': [
      'MOARK_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://moark.com/v1',
    'doc': 'https://moark.com/docs/openapi/v1#tag/%E6%96%87%E6%9C%AC%E7%94%9F%E6%88%90',
  },
  {
    'id': 'modal',
    'name': 'Modal',
    'env': [
      'MODAL_PROXY_TOKEN',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://inference.us-west.modal.direct/v1',
    'doc': 'https://modal.com/docs/guide/endpoints',
  },
  {
    'id': 'model-oracle-ai',
    'name': 'Model Oracle AI',
    'env': [
      'MODEL_ORACLE_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.modeloracle.com/api/v1',
    'doc': 'https://modeloracle.com/setup/',
  },
  {
    'id': 'modelis',
    'name': 'Modelis',
    'env': [
      'MODELIS_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://modelishub.com/v1',
    'doc': 'https://modelishub.com/pricing',
  },
  {
    'id': 'modelscope',
    'name': 'ModelScope',
    'env': [
      'MODELSCOPE_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api-inference.modelscope.cn/v1',
    'doc': 'https://modelscope.cn/docs/model-service/API-Inference/intro',
  },
  {
    'id': 'moonshotai',
    'name': 'Moonshot AI',
    'env': [
      'MOONSHOT_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.moonshot.ai/v1',
    'doc': 'https://platform.moonshot.ai/docs/api/chat',
  },
  {
    'id': 'moonshotai-cn',
    'name': 'Moonshot AI (China)',
    'env': [
      'MOONSHOT_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.moonshot.cn/v1',
    'doc': 'https://platform.moonshot.cn/docs/api/chat',
  },
  {
    'id': 'morph',
    'name': 'Morph',
    'env': [
      'MORPH_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.morphllm.com/v1',
    'doc': 'https://docs.morphllm.com/api-reference/introduction',
  },
  {
    'id': 'nano-gpt',
    'name': 'NanoGPT',
    'env': [
      'NANO_GPT_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://nano-gpt.com/api/v1',
    'doc': 'https://docs.nano-gpt.com',
  },
  {
    'id': 'nearai',
    'name': 'NEAR AI Cloud',
    'env': [
      'NEARAI_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://cloud-api.near.ai/v1',
    'doc': 'https://docs.near.ai/',
  },
  {
    'id': 'nebius',
    'name': 'Nebius Token Factory',
    'env': [
      'NEBIUS_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.tokenfactory.nebius.com/v1',
    'doc': 'https://docs.tokenfactory.nebius.com/',
  },
  {
    'id': 'neon',
    'name': 'Neon',
    'env': [
      'NEON_AI_GATEWAY_BASE_URL',
      'NEON_AI_GATEWAY_TOKEN',
    ],
    'protocol': 'openai-completions',
    'baseURL': '{env:NEON_AI_GATEWAY_BASE_URL}/v1',
    'doc': 'https://neon.com/docs',
  },
  {
    'id': 'neosmith',
    'name': 'NeoSmith',
    'env': [
      'NEOSMITH_API_KEY',
    ],
    'protocol': 'openai-responses',
    'baseURL': 'https://router.neosmith.ai/v1',
    'doc': 'https://neosmith.ai/docs',
  },
  {
    'id': 'neuralwatt',
    'name': 'Neuralwatt',
    'env': [
      'NEURALWATT_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.neuralwatt.com/v1',
    'doc': 'https://portal.neuralwatt.com/docs',
  },
  {
    'id': 'nova',
    'name': 'Nova',
    'env': [
      'NOVA_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.nova.amazon.com/v1',
    'doc': 'https://nova.amazon.com/dev/documentation',
  },
  {
    'id': 'novita-ai',
    'name': 'NovitaAI',
    'env': [
      'NOVITA_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.novita.ai/openai',
    'doc': 'https://novita.ai/docs/guides/introduction',
  },
  {
    'id': 'nvidia',
    'name': 'Nvidia',
    'env': [
      'NVIDIA_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://integrate.api.nvidia.com/v1',
    'doc': 'https://docs.api.nvidia.com/nim/',
  },
  {
    'id': 'ofox',
    'name': 'Ofox',
    'env': [
      'OFOX_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.ofox.ai/v1',
    'doc': 'https://ofox.ai/docs',
  },
  {
    'id': 'ollama',
    'name': 'Ollama (Local)',
    'env': [
      'OLLAMA_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'http://127.0.0.1:11434/v1',
    'doc': 'https://ollama.com',
  },
  {
    'id': 'ollama-cloud',
    'name': 'Ollama Cloud',
    'env': [
      'OLLAMA_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://ollama.com/v1',
    'doc': 'https://docs.ollama.com/cloud',
  },
  {
    'id': 'openai',
    'name': 'OpenAI',
    'env': [
      'OPENAI_API_KEY',
    ],
    'protocol': 'openai-responses',
    'baseURL': 'https://api.openai.com/v1',
    'doc': 'https://platform.openai.com/docs/models',
  },
  {
    'id': 'opencode-go',
    'name': 'OpenCode Go',
    'env': [
      'OPENCODE_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://opencode.ai/zen/go/v1',
    'doc': 'https://opencode.ai/docs/zen',
  },
  {
    'id': 'opencode',
    'name': 'OpenCode Zen',
    'env': [
      'OPENCODE_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://opencode.ai/zen/v1',
    'doc': 'https://opencode.ai/docs/zen',
  },
  {
    'id': 'openreason',
    'name': 'OpenReason',
    'env': [
      'OPENREASON_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.openreason.app/v1',
    'doc': 'https://openreason.app/docs',
  },
  {
    'id': 'openrouter',
    'name': 'OpenRouter',
    'env': [
      'OPENROUTER_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://openrouter.ai/api/v1',
    'doc': 'https://openrouter.ai/models',
  },
  {
    'id': 'opper',
    'name': 'Opper',
    'env': [
      'OPPER_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.opper.ai/v3/compat',
    'doc': 'https://opper.ai/models',
  },
  {
    'id': 'orcarouter',
    'name': 'OrcaRouter',
    'env': [
      'ORCAROUTER_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.orcarouter.ai/v1',
    'doc': 'https://docs.orcarouter.ai',
  },
  {
    'id': 'ovhcloud',
    'name': 'OVHcloud AI Endpoints',
    'env': [
      'OVHCLOUD_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://oai.endpoints.kepler.ai.cloud.ovh.net/v1',
    'doc': 'https://www.ovhcloud.com/en/public-cloud/ai-endpoints/catalog//',
  },
  {
    'id': 'pendra',
    'name': 'Pendra',
    'env': [
      'PENDRA_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.pendra.ai/api/v1',
    'doc': 'https://pendra.ai/docs/integrations/opencode',
  },
  {
    'id': 'perplexity',
    'name': 'Perplexity',
    'env': [
      'PERPLEXITY_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': '',
    'doc': 'https://docs.perplexity.ai',
  },
  {
    'id': 'perplexity-agent',
    'name': 'Perplexity Agent',
    'env': [
      'PERPLEXITY_API_KEY',
    ],
    'protocol': 'openai-responses',
    'baseURL': 'https://api.perplexity.ai/v1',
    'doc': 'https://docs.perplexity.ai/docs/agent-api/models',
  },
  {
    'id': 'pioneer',
    'name': 'Pioneer',
    'env': [
      'PIONEER_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.pioneer.ai/v1',
    'doc': 'https://agent.pioneer.ai/llms.txt',
  },
  {
    'id': 'poe',
    'name': 'Poe',
    'env': [
      'POE_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.poe.com/v1',
    'doc': 'https://creator.poe.com/docs/external-applications/openai-compatible-api',
  },
  {
    'id': 'poolside',
    'name': 'Poolside',
    'env': [
      'POOLSIDE_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://inference.poolside.ai/v1',
    'doc': 'https://platform.poolside.ai',
  },
  {
    'id': 'privatemode-ai',
    'name': 'Privatemode AI',
    'env': [
      'PRIVATEMODE_API_KEY',
      'PRIVATEMODE_ENDPOINT',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'http://localhost:8080/v1',
    'doc': 'https://docs.privatemode.ai/api/overview',
  },
  {
    'id': 'qihang-ai',
    'name': 'QiHang',
    'env': [
      'QIHANG_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.qhaigc.net/v1',
    'doc': 'https://www.qhaigc.net/docs',
  },
  {
    'id': 'qiniu-ai',
    'name': 'Qiniu',
    'env': [
      'QINIU_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.qnaigc.com/v1',
    'doc': 'https://developer.qiniu.com/aitokenapi',
  },
  {
    'id': 'qvac',
    'name': 'QVAC',
    'env': [
      'QVAC_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': '',
    'doc': 'https://www.npmjs.com/package/@qvac/ai-sdk-provider',
  },
  {
    'id': 'regolo-ai',
    'name': 'Regolo AI',
    'env': [
      'REGOLO_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.regolo.ai/v1',
    'doc': 'https://docs.regolo.ai/',
  },
  {
    'id': 'requesty',
    'name': 'Requesty',
    'env': [
      'REQUESTY_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://router.requesty.ai/v1',
    'doc': 'https://requesty.ai/solution/llm-routing/models',
  },
  {
    'id': 'routing-run',
    'name': 'routing.run',
    'env': [
      'ROUTING_RUN_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.routing.run/v1',
    'doc': 'https://docs.routing.run/api-reference/models',
  },
  {
    'id': 'runinfra',
    'name': 'RunInfra',
    'env': [
      'RUNINFRA_GATEWAY_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.runinfra.ai/v1',
    'doc': 'https://runinfra.ai/docs',
  },
  {
    'id': 'sakana',
    'name': 'Sakana AI',
    'env': [
      'SAKANA_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.sakana.ai/v1',
    'doc': 'https://console.sakana.ai/models',
  },
  {
    'id': 'salad-cloud',
    'name': 'SaladCloud AI Gateway',
    'env': [
      'SALAD_CLOUD_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': '',
    'doc': 'https://docs.salad.com/ai-gateway/explanation/overview',
  },
  {
    'id': 'sap-ai-core',
    'name': 'SAP AI Core',
    'env': [
      'AICORE_SERVICE_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': '',
    'doc': 'https://help.sap.com/docs/sap-ai-core',
  },
  {
    'id': 'sarvam',
    'name': 'Sarvam AI',
    'env': [
      'SARVAM_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.sarvam.ai/v1',
    'doc': 'https://docs.sarvam.ai/api-reference-docs/getting-started/models',
  },
  {
    'id': 'scaleway',
    'name': 'Scaleway',
    'env': [
      'SCALEWAY_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.scaleway.ai/v1',
    'doc': 'https://www.scaleway.com/en/docs/generative-apis/',
  },
  {
    'id': 'scnet-token-plan',
    'name': 'SCNet Token Plan',
    'env': [
      'SCNET_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.scnet.cn/api/llm/v1',
    'doc': 'https://www.scnet.cn/ac/openapi/doc/2.0/moduleapi/plans/token-plan.html',
  },
  {
    'id': 'scx-ai',
    'name': 'SCX.ai',
    'env': [
      'SCX_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.scx.ai/v1',
    'doc': 'https://platform.scx.ai/docs',
  },
  {
    'id': 'siliconflow',
    'name': 'SiliconFlow',
    'env': [
      'SILICONFLOW_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.siliconflow.com/v1',
    'doc': 'https://cloud.siliconflow.com/models',
  },
  {
    'id': 'siliconflow-cn',
    'name': 'SiliconFlow (China)',
    'env': [
      'SILICONFLOW_CN_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.siliconflow.cn/v1',
    'doc': 'https://cloud.siliconflow.com/models',
  },
  {
    'id': 'snowflake-cortex',
    'name': 'Snowflake Cortex',
    'env': [
      'SNOWFLAKE_ACCOUNT',
      'SNOWFLAKE_CORTEX_PAT',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://{env:SNOWFLAKE_ACCOUNT}.snowflakecomputing.com/api/v2/cortex/v1',
    'doc': 'https://docs.snowflake.com/en/user-guide/snowflake-cortex/cortex-rest-api',
  },
  {
    'id': 'stackit',
    'name': 'STACKIT',
    'env': [
      'STACKIT_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.openai-compat.model-serving.eu01.onstackit.cloud/v1',
    'doc': 'https://docs.stackit.cloud/products/data-and-ai/ai-model-serving/basics/available-shared-models',
  },
  {
    'id': 'standardcompute',
    'name': 'Standard Compute',
    'env': [
      'STANDARDCOMPUTE_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.stdcmpt.com/v1',
    'doc': 'https://standardcompute.com/models',
  },
  {
    'id': 'stepfun',
    'name': 'StepFun (China)',
    'env': [
      'STEPFUN_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.stepfun.com/v1',
    'doc': 'https://platform.stepfun.com/docs/zh/overview/concept',
  },
  {
    'id': 'stepfun-ai',
    'name': 'StepFun (Global)',
    'env': [
      'STEPFUN_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.stepfun.ai/v1',
    'doc': 'https://platform.stepfun.ai/docs/en/overview/concept',
  },
  {
    'id': 'stepfun-step-plan',
    'name': 'StepFun Step Plan (China)',
    'env': [
      'STEPFUN_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.stepfun.com/step_plan/v1',
    'doc': 'https://platform.stepfun.com/docs/zh/step-plan/integrations/reasoning-api',
  },
  {
    'id': 'stepfun-ai-step-plan',
    'name': 'StepFun Step Plan (Global)',
    'env': [
      'STEPFUN_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.stepfun.ai/step_plan/v1',
    'doc': 'https://platform.stepfun.ai/docs/en/step-plan/integrations/reasoning-api',
  },
  {
    'id': 'subconscious',
    'name': 'Subconscious',
    'env': [
      'SUBCONSCIOUS_API_KEY',
    ],
    'protocol': 'anthropic-messages',
    'baseURL': 'https://api.subconscious.dev/v1',
    'doc': 'https://docs.subconscious.dev',
  },
  {
    'id': 'submodel',
    'name': 'submodel',
    'env': [
      'SUBMODEL_INSTAGEN_ACCESS_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://llm.submodel.ai/v1',
    'doc': 'https://submodel.gitbook.io',
  },
  {
    'id': 'synthetic',
    'name': 'Synthetic',
    'env': [
      'SYNTHETIC_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.synthetic.new/openai/v1',
    'doc': 'https://synthetic.new/pricing',
  },
  {
    'id': 'tencent-coding-plan',
    'name': 'Tencent Coding Plan (China)',
    'env': [
      'TENCENT_CODING_PLAN_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.lkeap.cloud.tencent.com/coding/v3',
    'doc': 'https://cloud.tencent.com/document/product/1772/128947',
  },
  {
    'id': 'tencent-token-plan',
    'name': 'Tencent Token Plan',
    'env': [
      'TENCENT_TOKEN_PLAN_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.lkeap.cloud.tencent.com/plan/v3',
    'doc': 'https://cloud.tencent.com/document/product/1823/130060',
  },
  {
    'id': 'tencent-tokenhub',
    'name': 'Tencent TokenHub',
    'env': [
      'TENCENT_TOKENHUB_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://tokenhub.tencentmaas.com/v1',
    'doc': 'https://cloud.tencent.com/document/product/1823/130050',
  },
  {
    'id': 'tensorx',
    'name': 'TensorX',
    'env': [
      'TENSORX_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.tensorx.ai/v1',
    'doc': 'https://docs.tensorx.ai/',
  },
  {
    'id': 'the-grid-ai',
    'name': 'The Grid AI',
    'env': [
      'THEGRID_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.thegrid.ai/v1',
    'doc': 'https://thegrid.ai/docs',
  },
  {
    'id': 'thinkingmachines',
    'name': 'Thinking Machines',
    'env': [
      'TINKER_API_KEY',
    ],
    'protocol': 'anthropic-messages',
    'baseURL': 'https://tinker.thinkingmachines.dev/services/tinker-prod/anthropic/api/v1',
    'doc': 'https://tinker-docs.thinkingmachines.ai/tinker/compatible-apis/anthropic/',
  },
  {
    'id': 'tinfoil',
    'name': 'Tinfoil',
    'env': [
      'TINFOIL_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://inference.tinfoil.sh/v1',
    'doc': 'https://docs.tinfoil.sh',
  },
  {
    'id': 'togetherai',
    'name': 'Together AI',
    'env': [
      'TOGETHER_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': '',
    'doc': 'https://docs.together.ai/docs/serverless-models',
  },
  {
    'id': 'tokengo',
    'name': 'TokenGo',
    'env': [
      'TOKENGO_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.tokengo.com/v1',
    'doc': 'https://www.tokengo.com/docs',
  },
  {
    'id': 'tokenrouter',
    'name': 'TokenRouter',
    'env': [
      'TOKENROUTER_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.tokenrouter.com/v1',
    'doc': 'https://www.tokenrouter.com/docs/tokenrouter-feature-guide/',
  },
  {
    'id': 'trustedrouter',
    'name': 'TrustedRouter',
    'env': [
      'TRUSTEDROUTER_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.trustedrouter.com/v1',
    'doc': 'https://trustedrouter.com/docs',
  },
  {
    'id': 'umans-ai',
    'name': 'Umans AI',
    'env': [
      'UMANS_AI_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.code.umans.ai/v1',
    'doc': 'https://app.umans.ai/offers/code/docs/orgs',
  },
  {
    'id': 'umans-ai-coding-plan',
    'name': 'Umans AI Coding Plan',
    'env': [
      'UMANS_AI_CODING_PLAN_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.code.umans.ai/v1',
    'doc': 'https://app.umans.ai/offers/code/docs',
  },
  {
    'id': 'unorouter',
    'name': 'UnoRouter',
    'env': [
      'UNOROUTER_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.unorouter.com/v1',
    'doc': 'https://unorouter.com/models',
  },
  {
    'id': 'upstage',
    'name': 'Upstage',
    'env': [
      'UPSTAGE_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.upstage.ai/v1/solar',
    'doc': 'https://developers.upstage.ai/docs/apis/chat',
  },
  {
    'id': 'v0',
    'name': 'v0',
    'env': [
      'V0_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': '',
    'doc': 'https://sdk.vercel.ai/providers/ai-sdk-providers/vercel',
  },
  {
    'id': 'vancine',
    'name': 'Vancine',
    'env': [
      'VANCINE_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://vancine.com/v1',
    'doc': 'https://vancine.com/docs',
  },
  {
    'id': 'venice',
    'name': 'Venice AI',
    'env': [
      'VENICE_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': '',
    'doc': 'https://docs.venice.ai',
  },
  {
    'id': 'vercel',
    'name': 'Vercel AI Gateway',
    'env': [
      'AI_GATEWAY_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': '',
    'doc': 'https://github.com/vercel/ai/tree/5eb85cc45a259553501f535b8ac79a77d0e79223/packages/gateway',
  },
  {
    'id': 'google-vertex',
    'name': 'Vertex',
    'env': [
      'GOOGLE_VERTEX_PROJECT',
      'GOOGLE_VERTEX_LOCATION',
      'GOOGLE_APPLICATION_CREDENTIALS',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://{location}-aiplatform.googleapis.com',
    'doc': 'https://cloud.google.com/vertex-ai/generative-ai/docs/models',
  },
  {
    'id': 'google-vertex-anthropic',
    'name': 'Vertex (Anthropic)',
    'env': [
      'GOOGLE_VERTEX_PROJECT',
      'GOOGLE_VERTEX_LOCATION',
      'GOOGLE_APPLICATION_CREDENTIALS',
    ],
    'protocol': 'anthropic-messages',
    'baseURL': '',
    'doc': 'https://cloud.google.com/vertex-ai/generative-ai/docs/partner-models/claude',
  },
  {
    'id': 'vivgrid',
    'name': 'Vivgrid',
    'env': [
      'VIVGRID_API_KEY',
    ],
    'protocol': 'openai-responses',
    'baseURL': 'https://api.vivgrid.com/v1',
    'doc': 'https://docs.vivgrid.com/models',
  },
  {
    'id': 'volcengine',
    'name': 'Volcengine Ark',
    'env': [
      'ARK_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://ark.cn-beijing.volces.com/api/v3',
    'doc': 'https://www.volcengine.com/docs/82379/1330310',
  },
  {
    'id': 'volcengine-coding-plan',
    'name': 'Volcengine Ark Coding Plan',
    'env': [
      'ARK_CODING_PLAN_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://ark.cn-beijing.volces.com/api/coding/v3',
    'doc': 'https://www.volcengine.com/docs/82379/1928261',
  },
  {
    'id': 'vultr',
    'name': 'Vultr',
    'env': [
      'VULTR_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.vultrinference.com/v1',
    'doc': 'https://api.vultrinference.com/',
  },
  {
    'id': 'wafer.ai',
    'name': 'Wafer',
    'env': [
      'WAFER_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://pass.wafer.ai/v1',
    'doc': 'https://docs.wafer.ai/wafer-pass',
  },
  {
    'id': 'watsonx',
    'name': 'watsonx.ai',
    'env': [
      'WATSONX_AI_APIKEY',
      'WATSONX_AI_PROJECT_ID',
    ],
    'protocol': 'openai-completions',
    'baseURL': '',
    'doc': 'https://www.ibm.com/docs/en/watsonx/saas?topic=solutions-supported-foundation-models',
  },
  {
    'id': 'wandb',
    'name': 'Weights & Biases',
    'env': [
      'WANDB_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.inference.wandb.ai/v1',
    'doc': 'https://docs.wandb.ai/guides/integrations/inference/',
  },
  {
    'id': 'xai',
    'name': 'xAI',
    'env': [
      'XAI_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.x.ai/v1',
    'doc': 'https://docs.x.ai/docs/models',
  },
  {
    'id': 'xiaomi',
    'name': 'Xiaomi',
    'env': [
      'XIAOMI_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.xiaomimimo.com/v1',
    'doc': 'https://platform.xiaomimimo.com/#/docs',
  },
  {
    'id': 'xiaomi-token-plan-cn',
    'name': 'Xiaomi Token Plan (China)',
    'env': [
      'XIAOMI_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://token-plan-cn.xiaomimimo.com/v1',
    'doc': 'https://platform.xiaomimimo.com/#/docs',
  },
  {
    'id': 'xiaomi-token-plan-ams',
    'name': 'Xiaomi Token Plan (Europe)',
    'env': [
      'XIAOMI_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://token-plan-ams.xiaomimimo.com/v1',
    'doc': 'https://platform.xiaomimimo.com/#/docs',
  },
  {
    'id': 'xiaomi-token-plan-sgp',
    'name': 'Xiaomi Token Plan (Singapore)',
    'env': [
      'XIAOMI_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://token-plan-sgp.xiaomimimo.com/v1',
    'doc': 'https://platform.xiaomimimo.com/#/docs',
  },
  {
    'id': 'xpersona',
    'name': 'Xpersona',
    'env': [
      'XPERSONA_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://www.xpersona.co/v1',
    'doc': 'https://www.xpersona.co/docs',
  },
  {
    'id': 'zai',
    'name': 'Z.AI',
    'env': [
      'ZHIPU_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.z.ai/api/paas/v4',
    'doc': 'https://docs.z.ai/guides/overview/pricing',
  },
  {
    'id': 'zai-coding-plan',
    'name': 'Z.AI Coding Plan',
    'env': [
      'ZHIPU_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.z.ai/api/coding/paas/v4',
    'doc': 'https://docs.z.ai/devpack/overview',
  },
  {
    'id': 'zeldoc',
    'name': 'Zeldoc',
    'env': [
      'ZELDOC_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://api.zeldoc.ai/v1',
    'doc': 'https://docs.zeldoc.ai',
  },
  {
    'id': 'zenifra',
    'name': 'Zenifra',
    'env': [
      'ZENIFRA_AI_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://ai.zenifra.com/v1',
    'doc': 'https://docs.zenifra.com',
  },
  {
    'id': 'zenmux',
    'name': 'ZenMux',
    'env': [
      'ZENMUX_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://zenmux.ai/api/v1',
    'doc': 'https://docs.zenmux.ai',
  },
  {
    'id': 'zhipuai',
    'name': 'Zhipu AI',
    'env': [
      'ZHIPU_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://open.bigmodel.cn/api/paas/v4',
    'doc': 'https://docs.z.ai/guides/overview/pricing',
  },
  {
    'id': 'zhipuai-coding-plan',
    'name': 'Zhipu AI Coding Plan',
    'env': [
      'ZHIPU_API_KEY',
    ],
    'protocol': 'openai-completions',
    'baseURL': 'https://open.bigmodel.cn/api/coding/paas/v4',
    'doc': 'https://docs.bigmodel.cn/cn/coding-plan/overview',
  },
] as const
