/**
 * `dsh service` (fork): manage the background Web instance as an OS service —
 * a systemd user unit on Linux, a launchd LaunchAgent on macOS — so the
 * Harness survives terminal exits and starts at login. The unit always runs
 * `web --foreground`, which forbids the launcher's attach path: a supervised
 * process must serve, never print-and-exit.
 *
 * The command never boots a profile. It reads `install-state.json` next to the
 * harness tree for the prefix, node binary, recorded unit, and bin directory.
 * `DSH_INSTALL_STATE` and `DSH_SERVICE_UNIT` override those for tests and for
 * parallel installs.
 * @module @deepseek-ai/dsh/service
 */

import { spawnSync } from 'node:child_process'
import { copyFileSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { readFile } from 'node:fs/promises'
import { homedir } from 'node:os'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { resolveDshHome } from '@deepseek-ai/dsh-home-paths'
import { webStatePath } from '@deepseek-ai/dsh-web-app/state'

/** The harness tree root this command runs from (source or built layout). */
const HARNESS_ROOT = fileURLToPath(new URL('../../..', import.meta.url))

/** Unit name on Linux and label on macOS when nothing else is recorded. */
const DEFAULT_LINUX_UNIT = 'dsh-web.service'
const DEFAULT_DARWIN_LABEL = 'com.enpoi.dsh-web'

/** The port the managed unit serves on; mirrors the web app default. */
const MANAGED_PORT = 3080

/** Marker proving a unit file is ours to overwrite. */
const GENERATED_MARKER_SYSTEMD = '# Generated by dsh service install'
const GENERATED_MARKER_PLIST = '<!-- Generated by dsh service install -->'

/** Fields read from the installer's state file. */
export interface InstallState {
  prefix?: string
  node?: string
  serviceUnit?: string | null
  binDir?: string
  dshHome?: string
}

/** Injected seams for {@link runService}; production uses the defaults. */
export interface ServiceDeps {
  platform?: NodeJS.Platform
  home?: string
  statePath?: string
  /** Runs one command, inheriting stdio; returns its exit code. */
  run?: (command: string, args: readonly string[]) => number
  /** Answers whether launchd already knows a domain target; used silently. */
  probeLoaded?: (domainTarget: string) => boolean
  /**
   * Answers whether a launchd GUI domain exists for the uid. Used only after a
   * failed bootstrap to distinguish a headless/SSH-only Mac from a real error.
   */
  probeGuiDomain?: (domain: string) => boolean
  stdout?: { write: (chunk: string) => unknown }
  stderr?: { write: (chunk: string) => unknown }
  /** Reads the tail of the launchd log file. */
  tailLog?: (path: string, lines: number) => string
}

/** Everything one rendered unit needs. */
export interface UnitSpec {
  prefix: string
  node: string
  /** Absolute path of the CLI entry the unit executes. */
  bin: string
  dshHome: string
  port: number
  /** Directory prepended to PATH for launchd, which inherits no shell. */
  binDir: string
}

/**
 * Render the systemd user unit.
 * @param spec - resolved paths and port.
 * @returns the unit file text with the generated marker first.
 */
export function renderSystemdUnit(spec: UnitSpec): string {
  return [
    GENERATED_MARKER_SYSTEMD + '; edits are overwritten only with --force.',
    '[Unit]',
    'Description=Enpoi Harness Web (dsh web)',
    'After=network-online.target',
    '',
    '[Service]',
    'Type=simple',
    `ExecStart=${spec.node} ${spec.bin} web --foreground --host 127.0.0.1 --port ${String(spec.port)} --no-open`,
    'Restart=on-failure',
    'RestartSec=2',
    `Environment=DSH_HOME=${spec.dshHome}`,
    '',
    '[Install]',
    'WantedBy=default.target',
    '',
  ].join('\n')
}

/**
 * Render the launchd LaunchAgent plist. `KeepAlive` restarts crashes only —
 * a clean exit (for example an unexpected attach-exit) must not respawn in a
 * loop. `PATH` is explicit because launchd agents inherit no login shell.
 * @param spec - resolved paths, port, label, and log destination.
 * @returns the plist document with the generated marker.
 */
export function renderLaunchdPlist(spec: UnitSpec & { label: string; logPath: string }): string {
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
    '<plist version="1.0">',
    '<dict>',
    '  ' + GENERATED_MARKER_PLIST,
    `  <key>Label</key><string>${spec.label}</string>`,
    '  <key>ProgramArguments</key>',
    '  <array>',
    `    <string>${spec.node}</string>`,
    `    <string>${spec.bin}</string>`,
    '    <string>web</string>',
    '    <string>--foreground</string>',
    '    <string>--host</string>',
    '    <string>127.0.0.1</string>',
    '    <string>--port</string>',
    `    <string>${String(spec.port)}</string>`,
    '    <string>--no-open</string>',
    '  </array>',
    '  <key>EnvironmentVariables</key>',
    '  <dict>',
    `    <key>PATH</key><string>${spec.binDir}:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>`,
    `    <key>DSH_HOME</key><string>${spec.dshHome}</string>`,
    '  </dict>',
    '  <key>RunAtLoad</key><true/>',
    '  <key>KeepAlive</key>',
    '  <dict>',
    '    <key>SuccessfulExit</key><false/>',
    '    <key>Crashed</key><true/>',
    '  </dict>',
    '  <key>ThrottleInterval</key><integer>5</integer>',
    `  <key>StandardOutPath</key><string>${spec.logPath}</string>`,
    `  <key>StandardErrorPath</key><string>${spec.logPath}</string>`,
    '</dict>',
    '</plist>',
    '',
  ].join('\n')
}

/** The rendered unit plus the paths the command needs to place it. */
interface ResolvedUnit {
  kind: 'systemd' | 'launchd'
  unit: string
  path: string
  content: string
  spec: UnitSpec & { label: string; logPath: string }
}

/** The command surface, as printed by `dsh service help`. */
export const SERVICE_USAGE = `Usage: dsh service <command> [options]

Commands:
  install [--force] [--no-start]   write the unit, enable it, and start it
  uninstall                        stop and remove the unit
  start | stop | restart           control the unit
  status                           unit state plus the running URL
  logs [--lines N]                 recent unit output (default 100 lines)
  help                             show this help

The unit runs \`dsh web --foreground\`; interactive \`dsh web\` attaches to it.
An existing unit without a generated marker is never overwritten without --force.
`

/**
 * Read the installer state file; `DSH_INSTALL_STATE` overrides its location.
 * @param override - explicit state path for tests.
 * @returns the parsed state, or undefined when absent or unreadable.
 */
export function readInstallState(override?: string): InstallState | undefined {
  const path = override ?? process.env.DSH_INSTALL_STATE ?? join(HARNESS_ROOT, '..', 'install-state.json')
  try {
    const parsed: unknown = JSON.parse(readFileSync(path, 'utf8'))
    if (typeof parsed !== 'object' || parsed === null) return undefined
    return parsed as InstallState
  } catch {
    return undefined
  }
}

/**
 * Build the unit description for this machine.
 * @param state - installer state (prefix, node, unit).
 * @param deps - platform, home, and unit overrides.
 * @returns the resolved unit, its file path, and its rendered content.
 */
export function resolveUnit(state: InstallState, deps: ServiceDeps = {}): ResolvedUnit {
  const platform = deps.platform ?? process.platform
  const home = deps.home ?? homedir()
  const dshHome = state.dshHome ?? resolveDshHome()
  const prefix = state.prefix ?? join(home, '.dsh')
  const binDir = state.binDir ?? join(home, '.local', 'bin')
  const runtimeNode = join(prefix, 'runtime', 'node', 'current', 'bin', 'node')
  const node = existsSync(runtimeNode) ? runtimeNode : state.node ?? process.execPath
  const bin = join(prefix, 'harness', 'current', 'apps', 'cli', 'lib', 'bin.js')
  const spec = { prefix, node, bin, dshHome, port: MANAGED_PORT, binDir }
  const unitOverride = recordedUnitName(process.env.DSH_SERVICE_UNIT)
  const recordedUnit = recordedUnitName(state.serviceUnit)
  if (platform === 'darwin') {
    const label = unitOverride ?? recordedUnit ?? DEFAULT_DARWIN_LABEL
    const logPath = join(dshHome, 'logs', 'web.log')
    return {
      kind: 'launchd',
      unit: label,
      path: join(home, 'Library', 'LaunchAgents', `${label}.plist`),
      content: renderLaunchdPlist({ ...spec, label, logPath }),
      spec: { ...spec, label, logPath },
    }
  }
  const unit = unitOverride ?? recordedUnit ?? DEFAULT_LINUX_UNIT
  return {
    kind: 'systemd',
    unit,
    path: join(home, '.config', 'systemd', 'user', unit),
    content: renderSystemdUnit(spec),
    spec: { ...spec, label: unit, logPath: join(dshHome, 'logs', 'web.log') },
  }
}

/**
 * A usable unit name from the environment or the state file. Blank strings and
 * values that are not a plain file name resolve to undefined so the caller's
 * default applies; `""` must never become the unit, or the unit path collapses
 * to the systemd/LaunchAgents directory itself.
 * @param value - recorded unit name or label.
 * @returns the trimmed name, or undefined when unusable.
 */
function recordedUnitName(value: string | null | undefined): string | undefined {
  if (typeof value !== 'string') return undefined
  const trimmed = value.trim()
  if (trimmed === '' || trimmed.includes('/') || trimmed.includes('\\')) return undefined
  return trimmed
}

/** Whether the file at `path` carries this service manager's generated marker. */
function unitGenerated(path: string, kind: 'systemd' | 'launchd'): boolean {
  const marker = kind === 'systemd' ? GENERATED_MARKER_SYSTEMD : GENERATED_MARKER_PLIST
  try {
    return readFileSync(path, 'utf8').includes(marker)
  } catch {
    return false
  }
}

/** Whether an existing unit file may be replaced. */
function unitReplaceable(path: string, kind: 'systemd' | 'launchd', force: boolean): boolean {
  if (!existsSync(path)) return true
  if (force) return true
  return unitGenerated(path, kind)
}

/** Record (or clear) the managed unit in the installer state file. */
function recordUnit(statePath: string | undefined, unit: string | null): void {
  const path = statePath ?? process.env.DSH_INSTALL_STATE ?? join(HARNESS_ROOT, '..', 'install-state.json')
  try {
    const parsed = JSON.parse(readFileSync(path, 'utf8')) as InstallState
    parsed.serviceUnit = unit
    writeFileSync(path, `${JSON.stringify(parsed, null, 2)}\n`)
  } catch {
    // No managed install (source checkout): nothing to record.
  }
}

/** Print the recorded URL when a live instance state file exists. */
async function printRunningUrl(stdout: { write: (chunk: string) => unknown }): Promise<void> {
  try {
    const parsed = JSON.parse(await readFile(webStatePath(), 'utf8')) as { url?: unknown; pid?: unknown }
    if (typeof parsed.url !== 'string' || typeof parsed.pid !== 'number') return
    process.kill(parsed.pid, 0)
    stdout.write(`dsh web: ${parsed.url}\n`)
  } catch {
    // No live state: the unit status is the whole answer.
  }
}

/** The default command runner: inherit stdio, answer the exit code. */
function defaultRun(command: string, args: readonly string[]): number {
  const result = spawnSync(command, [...args], { stdio: 'inherit' })
  if (result.error !== undefined) return 1
  return result.status ?? 1
}

/** The default log tail for launchd, which has no journal. */
function defaultTailLog(path: string, lines: number): string {
  try {
    const content = readFileSync(path, 'utf8')
    return content.split('\n').slice(-(lines + 1)).join('\n')
  } catch {
    return ''
  }
}

/**
 * Run one `dsh service` invocation.
 * @param args - raw arguments after `dsh service`.
 * @param deps - injected seams; every field defaults to production behavior.
 * @returns the process exit code.
 */
export async function runService(args: readonly string[], deps: ServiceDeps = {}): Promise<number> {
  const stdout = deps.stdout ?? process.stdout
  const stderr = deps.stderr ?? process.stderr
  const run = deps.run ?? defaultRun
  const platform = deps.platform ?? process.platform
  const command = args[0]
  // Refuse before help or state lookup: Node on Git Bash/MSYS2/Cygwin reports
  // win32, and no Windows service manager is supported.
  if (platform === 'win32') {
    stderr.write('dsh service: Windows is not supported (no systemd or launchd). Use WSL 2: run `wsl --install` in PowerShell, then run this command inside the WSL Linux shell.\n')
    return 1
  }
  if (command === undefined || command === 'help' || command === '-h' || command === '--help') {
    stdout.write(SERVICE_USAGE)
    return 0
  }
  const state = readInstallState(deps.statePath)
  if (state === undefined) {
    stderr.write(`dsh service: no managed install (no install-state.json next to ${HARNESS_ROOT}); run the installer first\n`)
    return 1
  }
  const unit = resolveUnit(state, deps)
  const force = args.includes('--force')
  const noStart = args.includes('--no-start')
  const isLaunchd = unit.kind === 'launchd'
  const uid = typeof process.getuid === 'function' ? process.getuid() : 0
  const guiDomain = `gui/${String(uid)}`
  const domainTarget = `${guiDomain}/${unit.unit}`
  /**
   * Explain a failed `launchctl bootstrap` with the exact next command. A
   * headless/SSH-only Mac has no GUI domain: the unit is still written and
   * loads at the next desktop login, so the failure is a deferral, not a dead
   * end. The probe is silent and only runs on failure.
   */
  const explainBootstrapFailure = (code: number): void => {
    const guiAvailable = deps.probeGuiDomain !== undefined
      ? deps.probeGuiDomain(guiDomain)
      : spawnSync('launchctl', ['print', guiDomain], { stdio: 'ignore' }).status === 0
    if (guiAvailable) {
      stderr.write(`dsh service: launchctl bootstrap failed (exit ${String(code)})\n`)
    } else {
      stderr.write(`dsh service: no GUI login session for ${guiDomain} (headless or SSH-only Mac); the unit is written and starts at the next desktop login\n`)
    }
    stderr.write(`dsh service: start it from a desktop session with: launchctl bootstrap ${guiDomain} ${unit.path}\n`)
  }
  /** Whether launchd already knows this label in the user's GUI domain. */
  const launchctlLoaded = (): boolean => {
    if (!isLaunchd) return false
    if (deps.probeLoaded !== undefined) return deps.probeLoaded(domainTarget)
    return spawnSync('launchctl', ['print', domainTarget], { stdio: 'ignore' }).status === 0
  }
  const tailLog = deps.tailLog ?? defaultTailLog

  switch (command) {
    case 'install': {
      if (!unitReplaceable(unit.path, unit.kind, force)) {
        stderr.write(`dsh service: ${unit.path} exists and was not generated by dsh service; rerun with --force to replace it\n`)
        return 1
      }
      // --force replaces a foreign unit, but never destroys it: the previous
      // file stays recoverable at <path>.backup.
      const foreignUnit = existsSync(unit.path) && !unitGenerated(unit.path, unit.kind)
      if (foreignUnit) {
        try {
          copyFileSync(unit.path, `${unit.path}.backup`)
        } catch (error) {
          stderr.write(`dsh service: could not back up ${unit.path}: ${(error as Error).message}\n`)
          return 1
        }
      }
      try {
        mkdirSync(dirname(unit.path), { recursive: true })
        // launchd does not create parents of StandardOutPath/StandardErrorPath;
        // a missing log directory makes the agent fail with EX_CONFIG.
        mkdirSync(dirname(unit.spec.logPath), { recursive: true })
        writeFileSync(unit.path, unit.content)
      } catch (error) {
        stderr.write(`dsh service: could not write ${unit.path}: ${(error as Error).message}\n`)
        return 1
      }
      recordUnit(deps.statePath, unit.unit)
      stdout.write(`dsh service: wrote ${unit.path}\n`)
      if (foreignUnit) stdout.write(`dsh service: previous unit backed up to ${unit.path}.backup\n`)
      if (isLaunchd) {
        if (launchctlLoaded()) run('launchctl', ['bootout', domainTarget])
        if (!noStart) {
          const code = run('launchctl', ['bootstrap', guiDomain, unit.path])
          if (code !== 0) {
            explainBootstrapFailure(code)
            return code
          }
        }
      } else {
        run('systemctl', ['--user', 'daemon-reload'])
        run('systemctl', ['--user', 'enable', unit.unit])
        // Best-effort: keep the user manager alive without an interactive session.
        if (process.env.USER !== undefined) run('loginctl', ['enable-linger', process.env.USER])
        if (!noStart) {
          const code = run('systemctl', ['--user', 'restart', unit.unit])
          if (code !== 0) return code
        }
      }
      stdout.write(`dsh service: ${unit.unit} installed${noStart ? '' : ' and started'}\n`)
      if (!noStart) await printRunningUrl(stdout)
      return 0
    }
    case 'uninstall': {
      // A unit this command did not write is never removed without --force,
      // so a hand-written service under the same name survives a stray call.
      if (existsSync(unit.path) && !unitGenerated(unit.path, unit.kind) && !force) {
        stderr.write(`dsh service: ${unit.path} was not generated by dsh service; rerun with --force to remove it\n`)
        return 1
      }
      if (isLaunchd) {
        if (run('launchctl', ['print', domainTarget]) === 0) run('launchctl', ['bootout', domainTarget])
      } else {
        run('systemctl', ['--user', 'stop', unit.unit])
        // Drop the enable symlink so a removed unit leaves no dangling link.
        run('systemctl', ['--user', 'disable', unit.unit])
      }
      try {
        rmSync(unit.path, { force: true })
      } catch (error) {
        stderr.write(`dsh service: could not remove ${unit.path}: ${(error as Error).message}\n`)
        return 1
      }
      if (!isLaunchd) run('systemctl', ['--user', 'daemon-reload'])
      recordUnit(deps.statePath, null)
      stdout.write(`dsh service: ${unit.unit} removed\n`)
      return 0
    }
    case 'start': {
      if (isLaunchd) {
        if (launchctlLoaded()) return run('launchctl', ['kickstart', '-k', domainTarget])
        const code = run('launchctl', ['bootstrap', guiDomain, unit.path])
        if (code !== 0) explainBootstrapFailure(code)
        return code
      }
      return run('systemctl', ['--user', 'start', unit.unit])
    }
    case 'stop': {
      if (isLaunchd) {
        if (!launchctlLoaded()) return 0
        return run('launchctl', ['bootout', domainTarget])
      }
      return run('systemctl', ['--user', 'stop', unit.unit])
    }
    case 'restart': {
      if (isLaunchd) {
        if (launchctlLoaded()) return run('launchctl', ['kickstart', '-k', domainTarget])
        const code = run('launchctl', ['bootstrap', guiDomain, unit.path])
        if (code !== 0) explainBootstrapFailure(code)
        return code
      }
      return run('systemctl', ['--user', 'restart', unit.unit])
    }
    case 'status': {
      const code = run(
        isLaunchd ? 'launchctl' : 'systemctl',
        isLaunchd ? ['print', domainTarget] : ['--user', 'status', unit.unit, '--no-pager'],
      )
      await printRunningUrl(stdout)
      return code
    }
    case 'logs': {
      const linesIndex = args.indexOf('--lines')
      const requested = linesIndex === -1 ? undefined : Number(args[linesIndex + 1])
      const lines = requested !== undefined && Number.isFinite(requested) && requested > 0 ? Math.floor(requested) : 100
      if (isLaunchd) {
        stdout.write(tailLog(unit.spec.logPath, lines))
        return 0
      }
      return run('journalctl', ['--user', '-u', unit.unit, '-n', String(lines), '--no-pager'])
    }
    default: {
      stderr.write(`dsh service: unknown command ${JSON.stringify(command)}\n`)
      stderr.write(SERVICE_USAGE)
      return 1
    }
  }
}
